---
- name: lab_config_backup
  hosts: golden_onyx
  gather_facts: no
  strategy: free
  connection: network_cli
  become: yes
  become_method: enable
  vars:
    #ansible_python_interpreter: /usr/bin/python3
    send_mail: False
    send_mail_secure: never
    ansible_network_os: onyx
    log_path: ./ansible.log
    debug: True
  tasks:

  - shell: date +%d_%m_%Y_%H_%M
    register: today

  - onyx_config:
     backup: yes
     backup_options:
       dir_path: "{{playbook_dir}}/backup/{{today.stdout}}"
       filename: "{{inventory_hostname}}.conf"
     commands:
        - show version concise
    register: files_backup

  - debug:
      var: files_backup
      verbosity: 2
  - debug:
       msg: "{{files_backup.backup_path}}"
       verbosity: 2

  - import_role:
        name: send_mail
    vars:
      mail_body: "Playbook used: {{ansible_play_name}} {{lookup('file', '{{files_backup.backup_path}}') }}"
      mail_server: "10.0.8.70"
      mail_subject: "GSO Network Golden lab: do-not-reply: {{ inventory_hostname }} configuration backup {{today.stdout}}"
      attach: "{{files_backup.backup_path}}"
      mail_from: "eddies@mellanox.com"
      mail_to_list:
         - eddies@mellanox.com
         - hagaia@mellanox.com
         - marlon@mellanox.com
         - denisyu@mellanox.com
         - oria@mellanox.com
      secure: "{{send_mail_secure}}"
    when: send_mail == "True"
    tags: send_mail

  - shell: cd {{files_backup.backup_path}} ; find . -maxdepth 1 -type f | cut -d'/' -f2
    register: files_to_send
    run_once: True

  - import_role:
        name: send_mail
    vars:
      mail_body: "Playbook used: {{ansible_play_name}} {{lookup('file', '{{files_backup.backup_path}}') }}"
      mail_server: "10.0.8.70"
      mail_subject: "GSO Network Golden lab: do-not-reply: Summary mail - all devices configuration files backup {{today.stdout}}"
      attach: "{{ files_to_send.stdout_lines }}"
      mail_from: "eddies@mellanox.com"
      mail_to_list:
         - eddies@mellanox.com
         - hagaia@mellanox.com
         - marlon@mellanox.com
         - denisyu@mellanox.com
         - oria@mellanox.com
      secure: "{{send_mail_secure}}"
    when: send_mail == "True"
    tags: send_mail
    run_once: True
