---
- name: onyx_golden_mlag_L2_playbook
  hosts: golden_onyx
  gather_facts: no
  strategy: free
  connection: network_cli
  become: yes
  become_method: enable
  vars:
    #ansible_python_interpreter: /usr/bin/python3
    send_mail: False
    ansible_network_os: onyx
    reset: factory
    clean_config: "True"
    wait_for_protocol_port: 22
    force_upgrade_downgrade: "True"
    local_path: "/mswg/release/sx_mlnx_os/"
    destination_folder: "/var/opt/tms/images"
    reload: "True"
    transfer_protocol: scp
    cpu: "X86_64"   # X86_64 | PPC_M460EX
    user: root
    password: password
    remote_ip: remote_server
    internal_network: "no"
    ntp_server: "10.4.0.134"
    version: 3.9.2006
    source_file: "{{local_path}}/sx_mlnx_os-{{ version }}/{{ cpu  }}/image-{{ cpu }}-{{ version }}.img"
    software_upgrade: "False"
    change_hostname: "True"
    ignore_net_errors: "True"
    log_path: ./ansible.log
    remote_server_ip: 10.228.129.138
    remote_server_user: eddies
    remote_server_password: "eddies11"
    debug: True
  tasks:
    - name: get_current_switch_version
      onyx_command:
        commands: show version concise
      register: curr_version

# save the onyx version as a fact named current_version
    - name: set_fact_current_version
      set_fact:
        current_version: "{{curr_version.stdout[0].split()[1] }}"

    - import_role:
        name: onyx_clean_config
      tags: clean_config
      when: clean_config == "True"

    - import_role:
        name: onyx_wait
      when: clean_config == "True"
      tags: wait1

    #- name: remove_known_host_entries
    #  onyx_config:
    #   commands: ssh client user admin known-host "{{remote_ip}}" remove

    - import_role:
        name: onyx_config
      vars:
        command:
            - no interface mgmt0 dhcp hostname
            - hostname {{ inventory_hostname }}
      when: change_hostname == "True"
      tags: change_hostname

# Passwordless SSH to vdi should already be in place
#    - name: get_img_file
#      shell: scp eddies@{{vdi}}:/{{source_file}} .
#      args:
#          chdir: /var/images/
#      run_once: True
#      delegate_to: localhost

    - name: check_mgmt_vrf
      onyx_command:
        commands: 'show vrf | include "Name: mgmt"'
      register: vrf_mgmt

    - name: fetch_image_to_switch_default_vrf
      onyx_command:
        commands: image fetch scp://{{remote_server_user}}:{{remote_server_password}}@{{remote_server_ip}}:/{{source_file}}
     
      tags: image_fetch
      when: 
        - software_upgrade == "True"
        - 'not vrf_mgmt.stdout is search("Name: mgmt")'

    - name: fetch_image_to_switch_default_vrf
      onyx_command:
        commands: image fetch vrf mgmt scp://{{remote_server_user}}:{{remote_server_password}}@{{remote_server_ip}}:/{{source_file}}
      tags: image_fetch
      when: 
       - software_upgrade == "True"
       - 'vrf_mgmt.stdout is search("Name: mgmt")'

    - import_role:
        name: onyx_upgrade
      when: software_upgrade == "True"
      tags: onyx_upgrade

    - import_role:
        name: onyx_wait
      tags: wait2
      when: software_upgrade == "True"

    - import_role:
        name: onyx_basic_lab_mgmt_config
      tags: basic_config

    - import_role:
        name: mlag
      tags: mlag

    - import_role:
       name: onyx_config
      vars:
       command:
         - configuration write
      when: change_hostname == "True"
      tags: change_hostname


    - import_role:
       name: send_mail
      vars:
       mail_body: "Playbook used: {{ansible_play_name}} "
       mail_server: "10.0.8.70"
       mail_subject: "GSO Network Golden lab: do-not-reply: {{ inventory_hostname }} has been successfully provisioned"
       mail_from: "eddies@nvidia.com"
       mail_to_list:
          - eddies@nvidia.com
          - hagaia@nvidia.com
          - marlon@nvidia.com
          - denisyu@nvidia.com
          - oria@nvidia.com
      when: send_mail == "True"
      tags: send_mail == "True"
